### PR TITLE
Fix ES6 module import

### LINKED ISSUE #132: ES6 module export
Is it planned to be webpack compatible?

### PR DESCRIPTION
**Pull request by alshakero**
Added `export default` to the TS files to support ES6 module styles without breaking CJS imports.

It should fix #132 and #129

### CODE REVIEW

File: src/json-patch-duplex.js [hunk 1]
```diff
@@ -198,20 +199,18 @@ var jsonpatch;
         return '/' + path;
     }
     var beforeDict = [];
-    var Mirror = (function () {
-        function Mirror(obj) {
+    class Mirror {
```
Comment (tomalec) [inline src/json-patch-duplex.js]: IE 11 does not support `class`. That's why we need to keep ES5-style class declarations, at least in js

File: src/json-patch-duplex.js [hunk 2]
```diff
@@ -268,10 +267,10 @@ var jsonpatch;
         if (callback) {
             observer.callback = callback;
             observer.next = null;
-            var dirtyCheck = function () {
+            var dirtyCheck = () => {
```
Comment (tomalec) [inline src/json-patch-duplex.js]: As above, in this branch we would like to keep IE11 support for quite long. We can drop it for `Proxy`-observer. But I feel arrow functions are not worth loosing x-platform support.

File: src/json-patch-duplex.js [hunk 3]
```diff
@@ -612,3 +609,6 @@ if (typeof exports !== "undefined") {
     exports.validator = jsonpatch.validator;
     exports.JsonPatchError = jsonpatch.JsonPatchError;
 }
+Object.defineProperty(exports, "__esModule", { value: true });
```
Comment (tomalec) [inline src/json-patch-duplex.js]: Shouldn't we move those lines inside `if (typeof exports !== "undefined") {`? -  not to break support for envs w/o exports

**Comment by tomalec** [comment]
Beside review comments, tests are failing

File: src/json-patch-duplex.js (hunk 2 above)
Comment (alshakero) [inline src/json-patch-duplex.js]: This is automatic from TS transpiler. Changed the config and now it's back 👍

File: src/json-patch-duplex.js (hunk 3 above)
Comment (alshakero) [inline src/json-patch-duplex.js]: hmmm, I don't know, changing it would break ES6 import. It produces this:
image

And here is the module code:
image

Making it `exports.default = jsonpatch` will produce the first error too.

File: package.json [hunk 4]
```diff
@@ -34,10 +34,11 @@
     "grunt-contrib-uglify": "~0.5.0",
     "jasmine": "^2.5.1",
     "jsdom": "^9.5.0",
-    "jsonfile": "^2.3.1"
+    "jsonfile": "^2.3.1",
+    "underscore": "^1.8.3"
   },
   "scripts": {
-    "tsc": "tsc src/json-patch-duplex.ts --noEmitHelpers && tsc src/json-patch.ts --noEmitHelpers",
+    "tsc": "tsc -w",
```
Comment (tomalec) [inline package.json]: I would leave `npm run tsc` just to compile, for watch, we can create another task

File: src/json-patch-duplex.js [hunk 5]
```diff
@@ -601,7 +602,11 @@ var jsonpatch;
         }
     }
     jsonpatch.validate = validate;
-})(jsonpatch || (jsonpatch = {}));
+    /* still referecing exports,
+    I guess there is no way around
+    https://github.com/Microsoft/TypeScript/issues/5341#issuecomment-149639676
+    */
+})(jsonpatch = exports.jsonpatch || (exports.jsonpatch = {}));
```
Comment (tomalec) [inline src/json-patch-duplex.js]: What about adding 
```js
if(typeof exports === 'undefined'){
    var exports = {};
}
```
?

To avoid `exports is not defined` errors

File: src/json-patch-duplex.ts [hunk 6]
```diff
@@ -677,4 +678,8 @@ if (typeof exports !== "undefined") {
   exports.validate = jsonpatch.validate;
   exports.validator = jsonpatch.validator;
   exports.JsonPatchError = jsonpatch.JsonPatchError;
-}
+
+  /* TS Transpiler automatically adds
+  .default  when referencing */
+  exports.default = jsonpatch;
```
Comment (tomalec) [inline src/json-patch-duplex.ts]: Can't we do `export default` in the module's code?

Comment (alshakero) [inline src/json-patch-duplex.ts]: If you mean `export default module jsonpatch {...` then no, it throws an error. if you mean 
`export default  jsonpatch` in the end of the module you get `[ts] An export assignment cannot be used in a namespace.`

Is there a certain problem with this one? `export default jsonpatch` can't be inside an `if`, and `exports.default = jsonpatch` is transpiled to exactly the same thing in the js.

File: src/json-patch-duplex.js (hunk 5 above)
Comment (alshakero) [inline src/json-patch-duplex.js]: Awesome idea.

File: package.json (hunk 4 above)
Comment (alshakero) [inline package.json]: Sure.

File: src/json-patch-duplex.ts (hunk 6 above)
Comment (tomalec) [inline src/json-patch-duplex.ts]: after https://github.com/Starcounter-Jack/JSON-Patch/pull/137#discussion_r93655435

yet another `if(typeof exports` is not needed, I thought about shortening even more.

**Comment by tomalec** [comment]
```js
if (typeof exports === 'undefined') {
    var exports = {};
}
```
Seems to be not so perfect solution as it leads to  `Uncaught ReferenceError: module is not defined` error in  https://github.com/PuppetJs/puppet-polymer-client demo

Could you take a look at it?

**Comment by alshakero** [comment]
@tomalec here you go. With this:

- [x] 1. All `npm test` specs passed.
- [x] 2. All PuppetJS specs passed.
- [x] 3. No errors in `puppet-polymer-client` anymore

**Comment by tomalec** [comment]
Looks like yet another hack on top of TS->JS, but let's leave it as it is, and hope it would get cleaner over time :)

**Comment by alshakero** [comment]
@tomalec aaaaaaand you're right again. This hack produced this #140. Will dig into it.
